export const WALLET_INSTALLED = "WALLET_INSTALLED";
export const CONNECT_WALLET = "CONNECT_WALLET";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_SHORT_ACCOUNTS = "GET_SHORT_ACCOUNTS";
export const GET_CHAIN = "GET_CHAIN";
